### ISSUE TITLE
New users missing critical options [BC-62436]

### ISSUE THREAD

**Issue by rfiguerasbcov** [rdacorporation/sharepoint-react-app-boilerplate#3]
Customer reported their new users are missing options to manage videos (add videos, manage playlist,etc.) on the BC Connector app for Sharepoint.

This issue is occurring for the users who have gained access to Brightcove Video Connector app for SharePoint in the last month. They’re getting only the Home Option.

Apart from new users, the rest of users are not facing this issue.

They are getting the all the options and able to use them without any issues

They also have a following questions:

Currently, there are 14 Admins an
[BC-62436_attachments.zip](https://github.com/rdacorporation/sharepoint-react-app-boilerplate/files/12703497/BC-62436_attachments.zip)
d 62 members in Brightcove Video Connector app for SharePoint. Do we have any limitation on providing access to Brightcove Video Connector app for SharePoint?

This is critical for them as this affects user’s workflow to manage BC videos from Sharepoint, as they have limited user accounts in VC

We increase their VC user limit for them, as a temporary workaround.

Attached are the worksheet provided by customer,

**Comment by rfiguerasbcov** [comment]
@Oceanswave fyi.

**Comment by Oceanswave** [comment]
@rfiguerasbcov This is an unrelated repository, thanks.
